#!/bin/bash
# Build React app and prepare Hostinger upload package
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY="$ROOT/deploy/package"
PUBLIC="$ROOT/client/public"

echo "Building React app..."
cd "$ROOT/client"
npm run build

echo "Preparing deploy package..."
rm -rf "$DEPLOY"
mkdir -p "$DEPLOY/api" "$DEPLOY/uploads" "$DEPLOY/scripts"

# React frontend (dist already includes public/ assets)
cp -r "$ROOT/client/dist/"* "$DEPLOY/"
cp "$ROOT/deploy/public_html.htaccess" "$DEPLOY/.htaccess"

# Backend
cp "$ROOT/api/"*.php "$DEPLOY/api/"
cp "$ROOT/api/.htaccess" "$DEPLOY/api/"
# db_config.php + mail_config.php generated by render_deploy_configs.php (build_zip.sh)
cp "$ROOT/api/db_config.example.php" "$DEPLOY/api/db_config.example.php"
cp "$ROOT/api/mail_config.example.php" "$DEPLOY/api/mail_config.example.php"
cp "$ROOT/api/deploy.config.example.php" "$DEPLOY/api/deploy.config.example.php" 2>/dev/null || true
rm -f "$DEPLOY/api/db_config.local.php" "$DEPLOY/api/deploy.config.php"

# One-time setup
cp "$ROOT/setup.php" "$DEPLOY/"
cp "$ROOT/schema.sql" "$DEPLOY/"
cp "$ROOT/scripts/production_reset.php" "$DEPLOY/scripts/"

# Uploads directory security
cp "$ROOT/uploads/.htaccess" "$DEPLOY/uploads/" 2>/dev/null || true
mkdir -p "$DEPLOY/uploads/shares"
cp "$ROOT/uploads/shares/.htaccess" "$DEPLOY/uploads/shares/" 2>/dev/null || true

# Never ship logs or install locks
rm -f "$DEPLOY/api/php_errors.log" "$DEPLOY/api/.installed"

cat > "$DEPLOY/HOSTINGER_UPLOAD.txt" << 'EOF'
GO-UNLISTED — HOSTINGER UPLOAD (zip & go)
=========================================

Credentials are already in api/db_config.php and api/mail_config.php.
See LOGIN_CREDENTIALS.txt for admin login.

1. Extract zip to public_html/ (or upload all files from deploy/package/)

2. FIRST TIME ONLY: Import schema.sql in phpMyAdmin

3. Visit https://go-unlisted.com/setup.php → Activate production site
   Then DELETE setup.php from the server.

4. Admin → Site Settings → Test SMTP (OTP email)

5. Test Register + Forgot MPIN on the live site

Re-deploy (site already live):
- Upload new zip — keep existing api/db_config.php if DB unchanged
- Do NOT re-import schema.sql or run setup.php again
EOF

echo ""
echo "✓ Deploy package ready: deploy/package/"
echo "  Upload ALL files inside deploy/package/ to Hostinger public_html/"
echo "  See HOSTINGER_UPLOAD.txt in that folder."
